### PR TITLE
chore(request): update http-service

### PR DESCRIPTION
**Pull request by DanielMSchmidt**
I choose to update this in a non-breaking way to ensure downwards compatability

### CODE REVIEW

**Comment by nLight** [comment]
@DanielMSchmidt I bet we also need updating https://github.com/dcos-labs/mesos-client/blob/master/src/stream/index.js#L6

**Comment by DanielMSchmidt** [comment]
@nLight why? I think we did not change it in [this PR](https://github.com/dcos-labs/http-service/pull/17/files)?

**Comment by nLight** [comment]
@juliangieseke let's see what future brings :yolo:

**Comment by nLight** [comment]
I will make a release

**Comment by nLight** [comment]
@dcos/mesos-client@0.2.5

**Pull request merged**
